name: Events Demo
on:
  pull_request:
    types: [opened, reopened, closed, reopened, edited]
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - '.github/workflows/*'
jobs:
  output-info:
    runs-on: Ubuntu-latest
    steps:
      - name: Output event data
        run: 'echo "Event: ${{ toJSON(github.event) }}"'
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
